apps/companies/urls.py
from django.urls import path

from .. import views

app_name = 'companies'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
]

b2b_invoicing_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('home.urls')),
    path('companies', include('apps.companies.urls')),
    path('users', include('apps.users.urls')),
    path('invoices', include('apps.invoices.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/companies/models.py
from operator import mod
from unicodedata import name
from django.db import models

# Create your models here.
class Company(models.Model):
    company_name = models.CharField(max_length=40)
    company_email = models.EmailField()
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return str(self.company_name)

apps/invoices/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

apps/companies/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'companies/index.html')

apps/invoices/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'invoices/index.html')

apps/users/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'users/index.html')

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="shortcut icon" href='{% static "logo.png" %}'> -->
    <title>{% block title %} {% endblock title %} </title>

    <style>
        .main {
            min-height: 100vh;
            /* height: 100%; */
        }
    </style>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'global/css/custom.css' %}">

    {% block style %}
    {% endblock style %}

</head>

<body>

    <div class="main">
        {% include 'snippets/header.html' %}

        {% block content %}
        {% endblock content %}
    </div>

    {% include 'snippets/footer.html' %}

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>

templates/companies/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} B2B | Companies {% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href='{% static "companies/css/style.css" %}'>
{% endblock style %}

{% block content %}
<h1>This is Companies Page</h1>
{% endblock content %}

templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} B2B | Home {% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href='{% static "home/css/style.css" %}'>
{% endblock style %}

{% block content %}
<h1>This is home</h1>
{% endblock content %}

templates/invoices/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} B2B | Invoices {% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href='{% static "invoices/css/style.css" %}'>
{% endblock style %}

{% block content %}
<h1>This is Invoices Page</h1>
{% endblock content %}

templates/snippets/footer.html
<style>
    footer {
        /* position: relative; */
        background-color: #00425B;
        color: white;
        text-align: center;
        height: 64px;
        padding: 20px 0;
        /* z-index: 100; */
    }
</style>

<!-- Footer starts -->
<footer>
    <div class="container">
        Copyright &copy; {% now 'Y'%} B2B Invoicing Platform
    </div>
</footer>
<!-- Footer ends -->

templates/snippets/header.html
<style>
    .header {
        /* position: relative; */
        background-color: #00425B;
        color: white;
        height: 70px;
        padding: 15px 0;
    }

    .header .nav-link {
        color: white;
    }
</style>

<!-- Header starts -->
<nav class="navbar navbar-expand-lg header">
    <a class="navbar-brand mx-5" href="{% url 'home:index' %}" style="color: white;">B2B Invoicing Platform</a>
    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav mx-4">
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'home:index' %}">Home</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'companies:index' %}">Companies</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'users:index' %}">Users</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'invoices:index' %}">Invoices</a>
            </li>
        </ul>
    </div>
</nav>
<!-- Header ends -->

templates/users/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} B2B | Users {% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href='{% static "users/css/style.css" %}'>
{% endblock style %}

{% block content %}
<h1>This is Users Page</h1>
{% endblock content %}